import type { Metadata } from "next";
import { Header } from '@/components/layout/header';
import { Footer } from '@/components/layout/footer';
import { Geist, Geist_Mono } from "next/font/google";
import { Providers } from '@/components/layout/provider';
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col" suppressHydrationWarning>
        <Providers>
          <Header />
          <main className="mt-16 mb-10 min-h-[calc(100vh-6.5rem)] overflow-y-auto px-6">
            {children}
          </main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}